---
- name: Check if oh-my-zsh is installed
  stat:
    path: $HOME/.oh-my-zsh
  register: ohmyzsh_installed

- name: Install oh-my-zsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: ohmyzsh_installed.stat.exists == False

- name: Check if .zshrc file exists in private repo
  stat:
    path: "{{ private_repository_path }}/.zshrc"
  register: zshrc_configured

- name: Copy zsh configuration file
  ansible.builtin.copy:
    src: "{{ private_repository_path }}/.zshrc"
    dest: $HOME/.zshrc
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: '0644'
  when: zshrc_configured.stat.exists == True