---
- name: Check if homebrew is installed
  stat:
    path: /opt/homebrew/
  register: homebrew_installed

- name: Install homebrew
  command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: homebrew_installed.stat.exists == False

- name: Install packages with homebrew
  when: 
    - homebrewpackages is defined
    - homebrewpackages is iterable
  community.general.homebrew:
    name: "{{ item.name}}"
    state: "{{ item.state | default('present')}}"
    force_formula: "{{ item.force_formula | default(omit)}}"
    install_options: "{{ item.install_options | default(omit)}}"
    path: "{{ item.path | default(omit)}}"
  loop: "{{ homebrewpackages }}"