- hosts: localhost
  connection: local

  vars_prompt:
    - name: password
      prompt: "Enter your user password"
      private: true

  vars_files:
    - ../../ansible-mac-configurator-private/private_vars.yml
  
  roles:
    - homebrew
    - oh-my-zsh