- hosts: localhost
  connection: local

  vars_prompt:
    - name: password
      prompt: "Enter your user password"
      private: true

  vars_files:
    - ../vars/custom_vars.yml
    - "{{ private_repository_path }}/private_vars.yml"
  
  roles:
    - homebrew
    - oh-my-zsh